In [9]:
import pandas as pd
import gzip

def parse(path):
    g = gzip.open(path, 'rb')
    for l in g:
        yield eval(l)

def getDF(path):
    i = 0
    df = {}
    positive_count = 0
    negative_count = 0
    neutral_count = 0
    for d in parse(path):
        if d['overall'] >= 4.0:
            if positive_count < 40000:
                positive_count += 1
                df[i] = d
                if positive_count % 10000 == 0:
                    print('positive: ', positive_count)
        elif d['overall'] == 3.0:
            if neutral_count < 40000:
                neutral_count += 1
                df[i] = d
                if neutral_count % 10000 == 0:
                    print('neutral: ', neutral_count)
        else:
            if negative_count < 40000:
                negative_count += 1
                df[i] = d
                if negative_count % 10000 == 0:
                    print('negative: ', negative_count)
        i += 1
        if positive_count + neutral_count + negative_count >= 40000 * 3:
            break
    return pd.DataFrame.from_dict(df, orient='index')

In [10]:
df = getDF('reviews_Electronics.json.gz')

positive:  10000
positive:  20000
positive:  30000
positive:  40000
negative:  10000
negative:  20000
neutral:  10000
negative:  30000
negative:  40000
neutral:  20000
neutral:  30000
neutral:  40000

In [11]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AKM1MP6P0OYPR,0132793040,"Vicki Gibson ""momo4""","[1, 1]",Corey Barker does a great job of explaining Bl...,5.0,Very thorough,1365811200,"04 13, 2013"
1,A2CX7LUOHB2NDG,0321732944,Bernie,"[0, 0]",While many beginner DVDs try to teach you ever...,5.0,Adobe Photoshop CS5 Crash Course with master P...,1341100800,"07 1, 2012"
2,A2NWSAGRHCP8N5,0439886341,bowmans2007,"[1, 1]",It never worked. My daughter worked to earn th...,1.0,absolutely horrible,1367193600,"04 29, 2013"
3,A2WNBOD3WNDNKT,0439886341,JAL,"[1, 1]",Some of the functions did not work properly. ...,3.0,Disappointing,1374451200,"07 22, 2013"
4,A1GI0U4ZRJA8WN,0439886341,Truthfull,"[4, 4]",Do not waste your money on this thing it is te...,1.0,TERRIBLE DONT WASTE YOUR MONEY,1334707200,"04 18, 2012"

In [12]:
df.to_csv('shortened_data.csv')